// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://femiwxezahajbxxjjnnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlbWl3eGV6YWhhamJ4eGpqbm5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjY4MjUsImV4cCI6MjA1Nzk0MjgyNX0.tD2ZwH_23XbToheHakHcBGRxtPl_I4Y4HgrQM-KrqT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);